[package]
name = "lumaread"
version = "0.1.0"
description = "A focused local reading companion"
authors = ["LumaRead"]
edition = "2021"

[lib]
name = "lumaread_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.3", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
