import { useCallback, useEffect, useRef, useState, type CSSProperties, type MouseEvent } from 'react'
import { BookOpen } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import type { DocumentBlock, DocumentSection, ImportedDocument, ReaderLocation } from '../../../domain/documents'
import { getDocumentRepository } from '../../../storage'
import { AdaptivePanel } from '../components/AdaptivePanel'
import { ReaderChrome } from '../components/ReaderChrome'
import { ReaderMoreMenu } from '../components/ReaderMoreMenu'
import { ReadingSettingsPanel } from '../components/ReadingSettingsPanel'
import { useReaderChromeVisibility } from '../useReaderChromeVisibility'
import { useReaderSettings } from '../useReaderSettings'
import { MEDIA_QUERIES, useMediaQuery } from '../../../app/responsive'
import { resolveSectionIndex } from './section-location'

type Loaded = { document: ImportedDocument; sections: DocumentSection[]; capabilities: import('../../../domain/documents').DocumentCapabilities }
function renderBlock(block: DocumentBlock) { if (block.type === 'heading') { const Heading = `h${block.level}` as const; return <Heading key={block.id}>{block.text}</Heading> } if (block.type === 'blockquote') return <blockquote key={block.id}>{block.text}</blockquote>; if (block.type === 'list-item') return <li key={block.id}>{block.text}</li>; if (block.type === 'page-break') return <hr aria-label="Page break" key={block.id} />; return <p key={block.id}>{block.text}</p> }
export function ImportedDocumentReader({ documentId }: { documentId: string }) {
  const navigate = useNavigate(); const isMobile = useMediaQuery(MEDIA_QUERIES.mobile); const [loaded, setLoaded] = useState<Loaded>(); const [error, setError] = useState<string>(); const [sectionIndex, setSectionIndex] = useState(0); const [settingsOpen, setSettingsOpen] = useState<HTMLButtonElement>(); const [moreOpen, setMoreOpen] = useState<HTMLButtonElement>(); const [tocOpen, setTocOpen] = useState<HTMLButtonElement>(); const { settings, setSettings } = useReaderSettings(); const { chromeRef, hide, reveal, visible } = useReaderChromeVisibility({ isMobile, overlayOpen: Boolean(settingsOpen || moreOpen || tocOpen) }); const locations = useRef(new Map<string, ReaderLocation>()); const timer = useRef<number | undefined>(undefined)
  useEffect(() => { let active = true; void (async () => { try { const repository = getDocumentRepository(); const [record, location] = await Promise.all([repository.getDocument(documentId), repository.getLocation(documentId)]); if (!record) throw new Error('This document is no longer available.'); if (!active) return; if (location) locations.current.set(location.sectionId, location); setLoaded({ document: record.document, sections: record.sections, capabilities: record.capabilities }); setSectionIndex(resolveSectionIndex(record.sections, location)) } catch (caught) { if (active) setError(caught instanceof Error ? caught.message : 'LumaRead could not open this document.') } })(); return () => { active = false } }, [documentId])
  const saveLocation = useCallback(() => { const section = loaded?.sections[sectionIndex]; if (!section || !loaded) return; const maximum = Math.max(1, document.documentElement.scrollHeight - window.innerHeight); const location: ReaderLocation = { documentId, sectionId: section.id, sectionIndex, progressPercent: Math.min(100, Math.round((window.scrollY / maximum) * 100)), updatedAt: new Date().toISOString() }; locations.current.set(section.id, location); void getDocumentRepository().saveLocation(location).catch(() => undefined) }, [documentId, loaded, sectionIndex])
  useEffect(() => { if (!loaded) return; const saved = locations.current.get(loaded.sections[sectionIndex]?.id ?? ''); requestAnimationFrame(() => window.scrollTo({ top: saved ? Math.max(0, document.documentElement.scrollHeight - window.innerHeight) * saved.progressPercent / 100 : 0 })); const onScroll = () => { window.clearTimeout(timer.current); timer.current = window.setTimeout(saveLocation, 650) }; window.addEventListener('scroll', onScroll, { passive: true }); return () => { window.removeEventListener('scroll', onScroll); window.clearTimeout(timer.current); saveLocation() } }, [loaded, saveLocation, sectionIndex])
  function changeSection(next: number) { saveLocation(); setSectionIndex(next); setTocOpen(undefined) }
  function readingAreaClick(event: MouseEvent<HTMLElement>) { if (event.defaultPrevented || window.getSelection()?.toString().trim()) return; const target = event.target as HTMLElement; if (target.closest('.reader-panel')) return; if (isMobile && (target === event.currentTarget || target.classList.contains('reader-article'))) { if (visible) hide(); else reveal() } else if (target === event.currentTarget) reveal() }
  const lineHeight = settings.lineHeight === 'compact' ? (isMobile ? 1.54 : 1.58) : settings.lineHeight === 'relaxed' ? (isMobile ? 1.84 : 1.88) : (isMobile ? 1.68 : 1.72)
  if (error) return <div className="reader-shell reader-message"><h1>Unable to open this document</h1><p>{error}</p><Link to="/library">Return to Library</Link></div>
  if (!loaded) return <div aria-live="polite" className="reader-shell reader-message"><p>Opening your document…</p></div>
  const section = loaded.sections[sectionIndex] ?? loaded.sections[0]
  return <div className="reader-shell"><ReaderChrome bookTitle={loaded.document.metadata.title} chapterLabel={section?.title ?? `Section ${(sectionIndex + 1)}`} chromeRef={chromeRef} isMobile={isMobile} onBack={() => navigate('/library')} onMore={(target) => setMoreOpen(target)} onSettings={(target) => setSettingsOpen(target)} visible={visible} />
    <main className="reader-main" onClick={readingAreaClick}><article aria-labelledby="reader-chapter-title" className="reader-article" style={{ '--reader-font-scale': settings.fontScale, '--reader-line-height': lineHeight, '--reader-font-family': settings.fontFamily === 'serif' ? 'var(--font-reading)' : 'var(--font-ui)' } as CSSProperties}><header className="reader-chapter-heading"><div className="reader-chapter-heading__mark"><BookOpen aria-hidden="true" size={16} />{loaded.document.format.toUpperCase()} document</div><h1 id="reader-chapter-title">{section?.title ?? loaded.document.metadata.title}</h1></header><div className="reader-prose">{section?.blocks.map(renderBlock)}</div>{loaded.sections.length > 1 && <nav aria-label="Document sections" className="reader-section-nav"><button disabled={sectionIndex === 0} onClick={() => changeSection(sectionIndex - 1)} type="button">Previous</button><span>{sectionIndex + 1} / {loaded.sections.length}</span><button disabled={sectionIndex === loaded.sections.length - 1} onClick={() => changeSection(sectionIndex + 1)} type="button">Next</button></nav>}</article></main>
    {settingsOpen && <AdaptivePanel anchorElement={settingsOpen} isMobile={isMobile} label="Reading settings" onClose={() => setSettingsOpen(undefined)} variant="settings"><ReadingSettingsPanel settings={settings} setSettings={setSettings} /></AdaptivePanel>}
    {moreOpen && <AdaptivePanel anchorElement={moreOpen} isMobile={isMobile} label="More reader options" onClose={() => setMoreOpen(undefined)} variant="more"><ReaderMoreMenu capabilities={loaded.capabilities} canOpenTableOfContents={loaded.sections.length > 1} onOpenTableOfContents={() => { setTocOpen(moreOpen); setMoreOpen(undefined) }} /></AdaptivePanel>}
    {tocOpen && <AdaptivePanel anchorElement={tocOpen} isMobile={isMobile} label="Table of contents" onClose={() => setTocOpen(undefined)} variant="toc"><nav className="reader-toc">{loaded.sections.map((item, index) => <button aria-current={index === sectionIndex ? 'page' : undefined} key={item.id} onClick={() => changeSection(index)} type="button">{item.title ?? `Section ${index + 1}`}</button>)}</nav></AdaptivePanel>}
  </div>
}
