import { useCallback, useEffect, useRef, useState, type CSSProperties, type MouseEvent, type PointerEvent } from 'react'
import { Link } from 'react-router-dom'
import { ReadingHelp, type ReadingHelpHandle } from '../../learning/ReadingHelp'
import { annotationAnchorKey, annotationLocationLabel, findAnnotationOverlap, normalizeReaderLocator, readerLocatorAnchorKey, type AnnotationColor, type Bookmark, type DocumentCapabilities, type DocumentSection, type ImportedDocument, type ReaderAnnotation, type ReaderLocation, type TextAnchorSegment } from '../../../domain'
import * as storage from '../../../storage'
import { getBookmarkRepository } from '../../../storage'
import { AdaptivePanel } from '../components/AdaptivePanel'
import { ReaderChrome } from '../components/ReaderChrome'
import { ReaderChromeRevealZone } from '../components/ReaderChromeRevealZone'
import { isReaderKeyboardEventBlocked, shouldToggleReaderChrome } from '../readerKeyboard'
import { isReaderSwipe, isSwipeBlockedTarget, readerSwipeBehavior, type SwipePoint } from '../swipeNavigation'
import { useReaderExit } from '../useReaderExit'
import { useReaderChromeVisibility } from '../useReaderChromeVisibility'
import { useReaderSettings } from '../useReaderSettings'
import { useElementSize } from '../useElementSize'
import { resolveReaderLayout } from '../readerLayout'
import { DocumentBlockRenderer } from './DocumentBlockRenderer'
import { PdfPage } from './PdfPage'
import { PdfPageNavigation } from './PdfPageNavigation'
import { PdfViewSettingsPanel } from './PdfViewSettingsPanel'
import { clampCustomScale, clampPdfPage } from './pdfScale'
import { usePdfDocument } from './usePdfDocument'
import { usePdfLocation, type PdfLocationState } from './usePdfLocation'
import { ReaderBookmarksPanel } from '../components/ReaderBookmarksPanel'
import { HighlightsNotesPanel } from '../components/HighlightsNotesPanel'
import { SelectionToolbar } from '../components/SelectionToolbar'
import { AnnotationEditor } from '../components/AnnotationEditor'
import { createTextAnchorFromSelection, recoverAnnotation } from '../annotation-anchor'
import { ReaderSearchPanel, type ReaderSearchPanelHandle } from '../components/ReaderSearchPanel'
import { createNavigationHistory } from '../reader-navigation'
import { useReaderSearchShortcut } from '../useReaderSearchShortcut'
import type { ReaderLocator } from '../../../domain'

type Props = { document: ImportedDocument; source: Blob; sections: DocumentSection[]; capabilities: DocumentCapabilities; initialLocation?: ReaderLocation; isMobile: boolean; onBack: () => void; navigateHome?: () => void }
function pdfAnnotationRepository() { try { const get = storage.getAnnotationRepository; return typeof get === 'function' ? get() : undefined } catch { return undefined } }
export function PdfDocumentReader({ document: imported, source, sections, capabilities, initialLocation, isMobile, onBack, navigateHome }: Props) {
  const helpRef = useRef<ReadingHelpHandle>(null)
  const [helpOpen, setHelpOpen] = useState(false)
  const exitHome = navigateHome ?? onBack
  const restored = initialLocation?.pdf
  const [state, setState] = useState<PdfLocationState>(() => ({ page: clampPdfPage(restored?.pageNumber ?? (initialLocation?.sectionIndex ?? 0) + 1, sections.length), mode: restored?.mode ?? 'original', zoomMode: restored?.zoomMode ?? (isMobile ? 'fit-width' : 'comfortable'), zoom: clampCustomScale(restored?.zoom ?? 1), rotation: restored?.rotation ?? 0 }))
  const [scale, setScale] = useState(1); const [pageError, setPageError] = useState(false); const [retry, setRetry] = useState(0); const [viewAnchor, setViewAnchor] = useState<HTMLButtonElement>(); const [moreAnchor, setMoreAnchor] = useState<HTMLButtonElement>(); const [annotationsAnchor, setAnnotationsAnchor] = useState<HTMLButtonElement>(); const [bookmarksAnchor, setBookmarksAnchor] = useState<HTMLButtonElement>(); const [searchAnchor, setSearchAnchor] = useState<HTMLButtonElement>(); const [hasSearchHistory, setHasSearchHistory] = useState(false); const [bookmarks, setBookmarks] = useState<Bookmark[]>([]); const [annotations, setAnnotations] = useState<ReaderAnnotation[]>([]); const [selectionAnchor, setSelectionAnchor] = useState<{ segments: TextAnchorSegment[]; quote: string; anchorKey: string }>(); const [selectionPosition, setSelectionPosition] = useState<{ top: number; left: number }>(); const [editor, setEditor] = useState<{ anchor: HTMLElement; annotation?: ReaderAnnotation; pending?: { segments: TextAnchorSegment[]; quote: string; anchorKey: string }; color: AnnotationColor }>(); const [originalLayoutNotice, setOriginalLayoutNotice] = useState(false); const [annotationMessage, setAnnotationMessage] = useState<string>(); const stageRef = useRef<HTMLElement>(null); const articleRef = useRef<HTMLElement>(null); const searchPanelRef = useRef<ReaderSearchPanelHandle>(null); const gestureStart = useRef<SwipePoint | undefined>(undefined); const navigationHistory = useRef(createNavigationHistory()); const navigationEntryKinds = useRef<Array<'search' | 'annotation'>>([]); const pdfAnnotationReturnStates = useRef<Array<{ state: PdfLocationState; windowScrollY: number; stageScrollTop: number }>>([]); const pendingAnnotationTarget = useRef<{ sectionId: string; blockId: string } | undefined>(undefined); const stageSize = useElementSize(stageRef); const { document, error } = usePdfDocument(source); const { settings } = useReaderSettings(); const { chromeRef, hide, reveal, visible } = useReaderChromeVisibility({ isMobile, overlayOpen: Boolean(helpOpen || viewAnchor || moreAnchor || annotationsAnchor || bookmarksAnchor || searchAnchor || selectionAnchor || editor) })
  const flushLocation = usePdfLocation(imported, sections.length, state)
  const resourceKey = `imported:${imported.id}`
  useEffect(() => { void getBookmarkRepository().listForResource(resourceKey).then(setBookmarks).catch(() => setBookmarks([])) }, [resourceKey])
  useEffect(() => { let repository: ReturnType<typeof storage.getAnnotationRepository> | undefined; try { repository = pdfAnnotationRepository() } catch { repository = undefined } if (!repository) return; let active = true; void repository.listForResource(resourceKey).then(async (items) => { const recovered = await Promise.all(items.map(async (item) => { const result = recoverAnnotation(item, sections); if (result.status === 'recovered' && result.annotation.anchorKey !== item.anchorKey) { try { return await repository!.update(item.id, { segments: result.segments, orphaned: false }) ?? result.annotation } catch { return result.annotation } } return result.annotation })); if (active) setAnnotations(recovered) }).catch(() => { if (active) setAnnotations([]) }); return () => { active = false } }, [resourceKey, sections])
  const changePageBy = useCallback((delta: number) => { clearSelection(); setEditor(undefined); setState((current) => ({ ...current, page: clampPdfPage(current.page + delta, sections.length) })) }, [sections.length])
  function pointerDown(event: PointerEvent<HTMLElement>) { if (event.pointerType !== 'touch' || state.mode !== 'original') return; const x = event.clientX; gestureStart.current = { x, y: event.clientY, pointerCount: event.isPrimary ? 1 : 2, startedAtEdge: x < 26 || x > window.innerWidth - 26, blockedTarget: isSwipeBlockedTarget(event.target) } }
  function pointerUp(event: PointerEvent<HTMLElement>) { const start = gestureStart.current; gestureStart.current = undefined; if (event.pointerType !== 'touch' || !start || !isReaderSwipe(start, { x: event.clientX, y: event.clientY }, window.getSelection()?.toString() ?? '') || readerSwipeBehavior('pdf', state.mode, sections.length) !== 'page') return; changePageBy(event.clientX < start.x ? 1 : -1) }
  const zoom = useCallback((delta: number) => setState((current) => ({ ...current, zoomMode: 'custom', zoom: clampCustomScale((current.zoomMode === 'custom' ? current.zoom : scale) + delta) })), [scale])
  const reportPageError = useCallback(() => setPageError(true), [])
  useReaderExit({ closeOverlay: () => { if (editor) setEditor(undefined); else if (selectionAnchor) clearSelection(); else if (searchAnchor) setSearchAnchor(undefined); else if (bookmarksAnchor) setBookmarksAnchor(undefined); else if (annotationsAnchor) setAnnotationsAnchor(undefined); else if (moreAnchor) setMoreAnchor(undefined); else setViewAnchor(undefined) }, flushLocation, navigateHome: exitHome, overlayOpen: Boolean(viewAnchor || moreAnchor || annotationsAnchor || bookmarksAnchor || searchAnchor || selectionAnchor || editor) })
  function currentLocator() { return { version: 1 as const, kind: 'pdf' as const, resourceKey, pageNumber: state.page } }
  function currentBookmark() { const locator = currentLocator(); const anchorKey = readerLocatorAnchorKey(locator); return bookmarks.find((bookmark) => { const normalized = normalizeReaderLocator(bookmark.locator); return normalized ? readerLocatorAnchorKey(normalized) === anchorKey : false }) }
  async function toggleBookmark() { const locator = currentLocator(); try { await getBookmarkRepository().toggleAtLocator({ resourceKey, locator, label: `Page ${state.page}`, excerpt: sections[state.page - 1]?.blocks[0]?.text.slice(0, 140) }); setBookmarks(await getBookmarkRepository().listForResource(resourceKey)) } catch { /* Local storage is optional; Reader remains usable. */ } }
  function openBookmarks(anchor: HTMLButtonElement) { clearSelection(); setEditor(undefined); setViewAnchor(undefined); setMoreAnchor(undefined); setAnnotationsAnchor(undefined); setSearchAnchor(undefined); setBookmarksAnchor(anchor) }
  function openSearch(anchor: HTMLButtonElement) { clearSelection(); setEditor(undefined); setViewAnchor(undefined); setMoreAnchor(undefined); setAnnotationsAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(anchor) }
  function openAnnotations(anchor: HTMLButtonElement) { clearSelection(); setEditor(undefined); setViewAnchor(undefined); setMoreAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(undefined); setAnnotationsAnchor(anchor) }
  function captureSelection() { if (state.mode !== 'reading') return; const result = createTextAnchorFromSelection(window.getSelection(), { sections, root: articleRef.current ?? undefined }); if ('reason' in result) return; const range = window.getSelection()?.getRangeAt(0); if (!range) return; const rect = range.getBoundingClientRect(); setSelectionAnchor(result); setSelectionPosition({ top: isMobile ? 0 : Math.max(12, rect.bottom + 8), left: isMobile ? 0 : Math.min(Math.max(12, rect.left), Math.max(12, window.innerWidth - 360)) }) }
  function clearSelection() { helpRef.current?.close(); window.getSelection()?.removeAllRanges(); setSelectionAnchor(undefined); setSelectionPosition(undefined) }
  useEffect(() => { const pending = pendingAnnotationTarget.current; const section = sections[state.page - 1]; if (!pending || state.mode !== 'reading' || section?.id !== pending.sectionId) return; pendingAnnotationTarget.current = undefined; const frame = window.requestAnimationFrame(() => { const target = Array.from(articleRef.current?.querySelectorAll<HTMLElement>('[data-reader-block-id]') ?? []).find((element) => element.dataset.readerBlockId === pending.blockId); target?.scrollIntoView({ block: 'center', behavior: 'auto' }) }); return () => window.cancelAnimationFrame(frame) }, [sections, state.mode, state.page])
  async function saveAnnotation(pending: { segments: TextAnchorSegment[]; quote: string; anchorKey: string }, color: AnnotationColor, note?: string) { const repository = pdfAnnotationRepository(); if (!repository || pending.segments.some((segment) => segment.sectionId !== sections[state.page - 1]?.id)) return; const anchorKey = annotationAnchorKey(pending.segments); const existing = annotations.find((annotation) => annotation.anchorKey === anchorKey); if (existing) { const segment = existing.segments[0]; const target = segment ? Array.from(articleRef.current?.querySelectorAll<HTMLElement>('[data-reader-block-id]') ?? []).find((element) => element.dataset.readerBlockId === segment.blockId) : articleRef.current; clearSelection(); setEditor({ anchor: target ?? articleRef.current!, annotation: existing, color: existing.color }); return } if (findAnnotationOverlap(annotations, pending.segments)) { setAnnotationMessage('This text overlaps an existing highlight.'); window.setTimeout(() => setAnnotationMessage(undefined), 2400); return } try { await repository.add({ resourceKey, segments: pending.segments, quote: pending.quote, color, note }); setAnnotations(await repository.listForResource(resourceKey)); clearSelection(); setEditor(undefined) } catch { setAnnotationMessage('This highlight could not be saved. You can continue reading.'); window.setTimeout(() => setAnnotationMessage(undefined), 2400) } }
  function openAnnotationEditor(annotation: ReaderAnnotation, target: HTMLElement) { clearSelection(); setEditor({ anchor: target, annotation, color: annotation.color }) }
  async function saveEditor(note: string, color: AnnotationColor) { const repository = pdfAnnotationRepository(); if (editor?.annotation && repository) { try { const updated = await repository.update(editor.annotation.id, { note: note.trim() || undefined, color }); if (updated) setAnnotations(await repository.listForResource(resourceKey)); setEditor(undefined) } catch { setAnnotationMessage('This note could not be saved. You can continue reading.') } } else if (editor?.pending) await saveAnnotation(editor.pending, color, note.trim() || undefined) }
  function openBookmark(bookmark: Bookmark) { setBookmarksAnchor(undefined); if (bookmark.locator.kind !== 'pdf') return; const pageNumber = bookmark.locator.pageNumber; setState((current) => ({ ...current, page: clampPdfPage(pageNumber, sections.length) })); window.requestAnimationFrame(() => stageRef.current?.scrollTo({ top: 0, behavior: 'auto' })) }
  function goToLocator(locator: ReaderLocator) { if (locator.kind !== 'pdf') return; setState((current) => ({ ...current, page: clampPdfPage(locator.pageNumber, sections.length) })); window.requestAnimationFrame(() => stageRef.current?.scrollTo({ top: 0, behavior: 'auto' })) }
  function openAnnotationFromList(annotation: ReaderAnnotation) { if (annotation.orphaned) return; const recovered = recoverAnnotation(annotation, sections); const first = recovered.status === 'recovered' ? recovered.segments[0] : undefined; const pageIndex = first ? sections.findIndex((section) => section.id === first.sectionId) : -1; if (!first || pageIndex < 0 || !sections[pageIndex].blocks.some((block) => block.id === first.blockId)) return; const current = currentLocator(); navigationHistory.current.push(current); navigationEntryKinds.current.push('annotation'); pdfAnnotationReturnStates.current.push({ state, windowScrollY: window.scrollY, stageScrollTop: stageRef.current?.scrollTop ?? 0 }); setHasSearchHistory(true); pendingAnnotationTarget.current = { sectionId: first.sectionId, blockId: first.blockId }; setAnnotationsAnchor(undefined); void flushLocation(); setState((currentState) => ({ ...currentState, mode: 'reading', page: pageIndex + 1 })) }
  function openSearchResult(result: import('../reader-search').ReaderSearchResult) { const current = currentLocator(); navigationHistory.current.push(current); navigationEntryKinds.current.push('search'); setHasSearchHistory(true); void flushLocation(); setSearchAnchor(undefined); goToLocator(result.locator) }
  function backFromSearch() { const previous = navigationHistory.current.back(); const kind = navigationEntryKinds.current.pop(); if (kind === 'annotation') { const annotationState = pdfAnnotationReturnStates.current.pop(); if (annotationState) { setState(annotationState.state); window.requestAnimationFrame(() => { if (annotationState.state.mode === 'reading') window.scrollTo({ top: annotationState.windowScrollY, behavior: 'auto' }); else stageRef.current?.scrollTo({ top: annotationState.stageScrollTop, behavior: 'auto' }) }); setHasSearchHistory(navigationHistory.current.canGoBack()); return } } if (previous) { setHasSearchHistory(navigationHistory.current.canGoBack()); goToLocator(previous) } else { setHasSearchHistory(false); onBack() } }
  useReaderSearchShortcut({ open: () => { const anchor = globalThis.document.querySelector<HTMLButtonElement>('[aria-label="Search in current book"]'); if (anchor) openSearch(anchor) }, focus: () => searchPanelRef.current?.focusAndSelect(), openAlready: Boolean(searchAnchor) })
  useEffect(() => { const onKey = (event: globalThis.KeyboardEvent) => { if (helpOpen || viewAnchor || moreAnchor || annotationsAnchor || bookmarksAnchor || searchAnchor || editor || selectionAnchor || event.repeat || isReaderKeyboardEventBlocked(event)) return; if (event.key === 'ArrowLeft' || event.key === 'PageUp') { event.preventDefault(); changePageBy(-1) } if (event.key === 'ArrowRight' || event.key === 'PageDown') { event.preventDefault(); changePageBy(1) } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [changePageBy, helpOpen, viewAnchor, moreAnchor, annotationsAnchor, bookmarksAnchor, searchAnchor, editor, selectionAnchor])
  const clickPage = (event: MouseEvent<HTMLElement>) => { if (!shouldToggleReaderChrome({ currentTarget: event.currentTarget, defaultPrevented: event.defaultPrevented, selectedText: window.getSelection()?.toString() ?? '', target: event.target })) return; if (isMobile) { if (visible) hide(); else reveal() } else reveal() }
  if (error) return <div className="reader-shell reader-message"><h1>Unable to open this PDF</h1><p>{error}</p><Link to="/library">Return to Library</Link></div>
  const label = `Page ${state.page} of ${sections.length}`
  const layout = resolveReaderLayout(settings, isMobile)
  const effectiveZoomMode = state.zoomMode === 'comfortable' && isMobile ? 'fit-width' : state.zoomMode
  return <div className="reader-shell pdf-reader" onClick={clickPage} onPointerCancel={() => { gestureStart.current = undefined }} onPointerDown={pointerDown} onPointerUp={(event) => { pointerUp(event); if (state.mode === 'original' && window.getSelection()?.toString().trim()) { setOriginalLayoutNotice(true); window.setTimeout(() => setOriginalLayoutNotice(false), 3000) } }}><ReaderChrome backLabel={hasSearchHistory ? 'Back to previous reading position' : 'Back to Library'} bookTitle={imported.metadata.title} chapterLabel={label} chromeRef={chromeRef} isMobile={isMobile} onBack={backFromSearch} onMore={(target) => { clearSelection(); setEditor(undefined); setViewAnchor(undefined); setAnnotationsAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(undefined); setMoreAnchor(target) }} onSettings={(target) => { clearSelection(); setEditor(undefined); setMoreAnchor(undefined); setAnnotationsAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(undefined); setViewAnchor(target) }} onToggleBookmark={() => { clearSelection(); setEditor(undefined); void toggleBookmark() }} onOpenBookmarks={openBookmarks} onOpenSearch={openSearch} bookmarkActive={Boolean(currentBookmark())} pdf visible={visible} /><ReaderChromeRevealZone onReveal={reveal} visible={visible} />
    <ReadingHelp key={`${resourceKey}:${state.page}:${state.mode}`} ref={helpRef} resourceKey={resourceKey} bookTitle={imported.metadata.title} sectionId={sections[state.page - 1]?.id} pageNumber={state.page} isMobile={isMobile} standaloneSelection={state.mode === 'original'} otherPanelOpen={Boolean(viewAnchor || moreAnchor || annotationsAnchor || bookmarksAnchor || searchAnchor || editor)} onOpen={() => { clearSelection(); setEditor(undefined); setViewAnchor(undefined); setMoreAnchor(undefined); setAnnotationsAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(undefined); setOriginalLayoutNotice(false) }} onActiveChange={setHelpOpen} />
    {state.mode === 'reading' ? <main className="reader-main" onPointerUp={captureSelection}><article className={`reader-article ${layout.className}`} data-reader-section-id={sections[state.page - 1]?.id} ref={articleRef} style={layout.styleVariables as CSSProperties}><header className="reader-chapter-heading"><p>Reading view — Beta<br />Complex layouts may change.</p></header><div className="reader-prose"><DocumentBlockRenderer annotations={annotations.filter((annotation) => !annotation.orphaned)} blocks={sections[state.page - 1]?.blocks ?? []} sectionId={sections[state.page - 1]?.id} onAnnotationClick={openAnnotationEditor} /></div></article></main> : <main className="pdf-reader__stage" ref={stageRef}><PdfPageNavigation chromeVisible={visible} isMobile={isMobile} onNext={() => changePageBy(1)} onPrevious={() => changePageBy(-1)} page={state.page} total={sections.length} />{pageError ? <div className="reader-message"><p>This PDF page could not be rendered.</p><button onClick={() => { setPageError(false); setRetry((value) => value + 1) }} type="button">Retry</button><button onClick={onBack} type="button">Return to Library</button></div> : document ? <PdfPage availableSize={stageSize} document={document} key={retry} onError={reportPageError} onScale={setScale} pageNumber={state.page} rotation={state.rotation} selectable={capabilities.supportsTextSelection} zoom={state.zoom} zoomMode={effectiveZoomMode} /> : <p>Loading original layout…</p>}</main>}
    {selectionAnchor && selectionPosition && <div className={`selection-toolbar-host${isMobile ? ' selection-toolbar-host--mobile' : ''}`} style={isMobile ? undefined : selectionPosition}><SelectionToolbar onLookup={() => helpRef.current?.openSelection()} isMobile={isMobile} onAddNote={() => { if (selectionAnchor && articleRef.current) { const pending = selectionAnchor; setSelectionAnchor(undefined); setSelectionPosition(undefined); setEditor({ anchor: articleRef.current, pending, color: 'lavender' }) } }} onCancel={clearSelection} onHighlight={(color) => { void saveAnnotation(selectionAnchor, color) }} /></div>}
    {viewAnchor && <AdaptivePanel anchorElement={viewAnchor} isMobile={isMobile} label="PDF view settings" onClose={() => setViewAnchor(undefined)} variant="settings"><PdfViewSettingsPanel mode={state.zoomMode} onMode={(zoomMode) => setState((current) => ({ ...current, zoomMode }))} onRotate={() => setState((current) => ({ ...current, rotation: (current.rotation + 90) % 360 }))} onZoom={zoom} percent={Math.round(scale * 100)} /></AdaptivePanel>}
    {moreAnchor && <AdaptivePanel anchorElement={moreAnchor} isMobile={isMobile} label="PDF options" onClose={() => setMoreAnchor(undefined)} variant="more"><section className="reader-more-menu"><h2>More</h2><button onClick={() => openAnnotations(moreAnchor)} type="button">Highlights &amp; Notes</button><button onClick={() => { clearSelection(); setEditor(undefined); setState((current) => ({ ...current, mode: current.mode === 'original' ? 'reading' : 'original' })); setMoreAnchor(undefined) }} disabled={!capabilities.reflowable} type="button">{state.mode === 'original' ? 'Reading view — Beta' : 'Original layout'} {!capabilities.reflowable && <span>No selectable text was found. OCR reading view is not available yet.</span>}</button><button disabled={state.page <= 1} onClick={() => changePageBy(-1)} type="button">Previous page</button><button disabled={state.page >= sections.length} onClick={() => changePageBy(1)} type="button">Next page</button></section></AdaptivePanel>}
    {bookmarksAnchor && <AdaptivePanel anchorElement={bookmarksAnchor} isMobile={isMobile} label="Bookmarks" onClose={() => setBookmarksAnchor(undefined)} variant="bookmarks"><ReaderBookmarksPanel bookmarks={bookmarks} onDelete={(bookmark) => { void getBookmarkRepository().remove(bookmark.id).then(async () => setBookmarks(await getBookmarkRepository().listForResource(resourceKey))).catch(() => undefined) }} onOpen={openBookmark} /></AdaptivePanel>}
    {annotationsAnchor && <AdaptivePanel anchorElement={annotationsAnchor} isMobile={isMobile} label="Highlights & Notes" onClose={() => setAnnotationsAnchor(undefined)} variant="more"><HighlightsNotesPanel annotations={annotations} locationLabel={(annotation) => annotationLocationLabel(annotation, sections)} onDelete={(annotation) => { const repository = pdfAnnotationRepository(); if (repository) void repository.remove(annotation.id).then(async () => setAnnotations(await repository.listForResource(resourceKey))).catch(() => undefined) }} onEdit={(annotation) => { const segment = annotation.segments[0]; const target = segment ? Array.from(articleRef.current?.querySelectorAll<HTMLElement>('[data-reader-block-id]') ?? []).find((element) => element.dataset.readerBlockId === segment.blockId) : undefined; setEditor({ anchor: target ?? annotationsAnchor, annotation, color: annotation.color }); setAnnotationsAnchor(undefined) }} onOpen={openAnnotationFromList} /></AdaptivePanel>}
    {editor && <AdaptivePanel anchorElement={editor.anchor} isMobile={isMobile} label={editor.annotation ? 'Edit highlight' : 'Add note'} onClose={() => setEditor(undefined)} variant="more"><AnnotationEditor annotation={editor.annotation} color={editor.color} note={editor.annotation?.note} onCancel={() => setEditor(undefined)} onColor={(color) => setEditor((current) => current ? { ...current, color } : current)} onDelete={editor.annotation ? () => { const repository = pdfAnnotationRepository(); if (repository) void repository.remove(editor.annotation!.id).then(async () => { setAnnotations(await repository.listForResource(resourceKey)); setEditor(undefined) }) } : undefined} onSave={(note, color) => { void saveEditor(note, color) }} quote={editor.annotation?.quote ?? editor.pending?.quote ?? ''} /></AdaptivePanel>}
    {searchAnchor && <AdaptivePanel anchorElement={searchAnchor} isMobile={isMobile} label="Search in current book" onClose={() => setSearchAnchor(undefined)} variant="search"><ReaderSearchPanel kind="pdf" onSelect={openSearchResult} ref={searchPanelRef} resourceKey={resourceKey} sections={sections} /></AdaptivePanel>}
    {annotationMessage && <p aria-live="polite" className="reader-annotation-message">{annotationMessage}</p>}{originalLayoutNotice && <p aria-live="polite" className="reader-annotation-message">Highlights and notes are currently available in Reading View.</p>}
  </div>
}
