import { useCallback, useEffect, useRef, useState, type CSSProperties, type MouseEvent } from 'react'
import { Link } from 'react-router-dom'
import { annotationLocationLabel, findAnnotationOverlap, normalizeReaderLocator, readerLocatorAnchorKey, type AnnotationColor, type Bookmark, type DocumentCapabilities, type DocumentSection, type ImportedDocument, type ReaderAnnotation, type ReaderLocation, type TextAnchorSegment } from '../../../domain'
import * as storage from '../../../storage'
import { getBookmarkRepository } from '../../../storage'
import { AdaptivePanel } from '../components/AdaptivePanel'
import { ReaderChrome } from '../components/ReaderChrome'
import { ReaderChromeRevealZone } from '../components/ReaderChromeRevealZone'
import { isReaderKeyboardEventBlocked, shouldToggleReaderChrome } from '../readerKeyboard'
import { useReaderExit } from '../useReaderExit'
import { useReaderChromeVisibility } from '../useReaderChromeVisibility'
import { useReaderSettings } from '../useReaderSettings'
import { useElementSize } from '../useElementSize'
import { resolveReaderLayout } from '../readerLayout'
import { DocumentBlockRenderer } from './DocumentBlockRenderer'
import { PdfPage } from './PdfPage'
import { PdfPageNavigation } from './PdfPageNavigation'
import { PdfViewSettingsPanel } from './PdfViewSettingsPanel'
import { clampCustomScale, clampPdfPage } from './pdfScale'
import { usePdfDocument } from './usePdfDocument'
import { usePdfLocation, type PdfLocationState } from './usePdfLocation'
import { ReaderBookmarksPanel } from '../components/ReaderBookmarksPanel'
import { HighlightsNotesPanel } from '../components/HighlightsNotesPanel'
import { SelectionToolbar } from '../components/SelectionToolbar'
import { AnnotationEditor } from '../components/AnnotationEditor'
import { createTextAnchorFromSelection } from '../annotation-anchor'
import { ReaderSearchPanel, type ReaderSearchPanelHandle } from '../components/ReaderSearchPanel'
import { createNavigationHistory } from '../reader-navigation'
import { useReaderSearchShortcut } from '../useReaderSearchShortcut'
import type { ReaderLocator } from '../../../domain'

type Props = { document: ImportedDocument; source: Blob; sections: DocumentSection[]; capabilities: DocumentCapabilities; initialLocation?: ReaderLocation; isMobile: boolean; onBack: () => void; navigateHome?: () => void }
export function PdfDocumentReader({ document: imported, source, sections, capabilities, initialLocation, isMobile, onBack, navigateHome }: Props) {
  const exitHome = navigateHome ?? onBack
  const restored = initialLocation?.pdf
  const [state, setState] = useState<PdfLocationState>(() => ({ page: clampPdfPage(restored?.pageNumber ?? (initialLocation?.sectionIndex ?? 0) + 1, sections.length), mode: restored?.mode ?? 'original', zoomMode: restored?.zoomMode ?? (isMobile ? 'fit-width' : 'comfortable'), zoom: clampCustomScale(restored?.zoom ?? 1), rotation: restored?.rotation ?? 0 }))
  const [scale, setScale] = useState(1); const [pageError, setPageError] = useState(false); const [retry, setRetry] = useState(0); const [viewAnchor, setViewAnchor] = useState<HTMLButtonElement>(); const [moreAnchor, setMoreAnchor] = useState<HTMLButtonElement>(); const [annotationsAnchor, setAnnotationsAnchor] = useState<HTMLButtonElement>(); const [bookmarksAnchor, setBookmarksAnchor] = useState<HTMLButtonElement>(); const [searchAnchor, setSearchAnchor] = useState<HTMLButtonElement>(); const [hasSearchHistory, setHasSearchHistory] = useState(false); const [bookmarks, setBookmarks] = useState<Bookmark[]>([]); const [annotations, setAnnotations] = useState<ReaderAnnotation[]>([]); const [selectionAnchor, setSelectionAnchor] = useState<{ segments: TextAnchorSegment[]; quote: string; anchorKey: string }>(); const [selectionPosition, setSelectionPosition] = useState<{ top: number; left: number }>(); const [editor, setEditor] = useState<{ anchor: HTMLElement; annotation?: ReaderAnnotation; pending?: { segments: TextAnchorSegment[]; quote: string; anchorKey: string }; color: AnnotationColor }>(); const [originalLayoutNotice, setOriginalLayoutNotice] = useState(false); const stageRef = useRef<HTMLElement>(null); const articleRef = useRef<HTMLElement>(null); const searchPanelRef = useRef<ReaderSearchPanelHandle>(null); const navigationHistory = useRef(createNavigationHistory()); const stageSize = useElementSize(stageRef); const { document, error } = usePdfDocument(source); const { settings } = useReaderSettings(); const { chromeRef, hide, reveal, visible } = useReaderChromeVisibility({ isMobile, overlayOpen: Boolean(viewAnchor || moreAnchor || annotationsAnchor || bookmarksAnchor || searchAnchor || selectionAnchor || editor) })
  const flushLocation = usePdfLocation(imported, sections.length, state)
  const resourceKey = `imported:${imported.id}`
  useEffect(() => { void getBookmarkRepository().listForResource(resourceKey).then(setBookmarks).catch(() => setBookmarks([])) }, [resourceKey])
  useEffect(() => { let repository: ReturnType<typeof storage.getAnnotationRepository> | undefined; try { repository = typeof storage.getAnnotationRepository === 'function' ? storage.getAnnotationRepository() : undefined } catch { repository = undefined } if (repository) void repository.listForResource(resourceKey).then(setAnnotations).catch(() => setAnnotations([])) }, [resourceKey])
  const changePageBy = useCallback((delta: number) => setState((current) => ({ ...current, page: clampPdfPage(current.page + delta, sections.length) })), [sections.length])
  const zoom = useCallback((delta: number) => setState((current) => ({ ...current, zoomMode: 'custom', zoom: clampCustomScale((current.zoomMode === 'custom' ? current.zoom : scale) + delta) })), [scale])
  const reportPageError = useCallback(() => setPageError(true), [])
  useReaderExit({ closeOverlay: () => { if (searchAnchor) setSearchAnchor(undefined); else if (bookmarksAnchor) setBookmarksAnchor(undefined); else if (annotationsAnchor) setAnnotationsAnchor(undefined); else if (moreAnchor) setMoreAnchor(undefined); else setViewAnchor(undefined) }, flushLocation, navigateHome: exitHome, overlayOpen: Boolean(viewAnchor || moreAnchor || annotationsAnchor || bookmarksAnchor || searchAnchor) })
  function currentLocator() { return { version: 1 as const, kind: 'pdf' as const, resourceKey, pageNumber: state.page } }
  function currentBookmark() { const locator = currentLocator(); const anchorKey = readerLocatorAnchorKey(locator); return bookmarks.find((bookmark) => { const normalized = normalizeReaderLocator(bookmark.locator); return normalized ? readerLocatorAnchorKey(normalized) === anchorKey : false }) }
  async function toggleBookmark() { const locator = currentLocator(); try { await getBookmarkRepository().toggleAtLocator({ resourceKey, locator, label: `Page ${state.page}`, excerpt: sections[state.page - 1]?.blocks[0]?.text.slice(0, 140) }); setBookmarks(await getBookmarkRepository().listForResource(resourceKey)) } catch { /* Local storage is optional; Reader remains usable. */ } }
  function openBookmarks(anchor: HTMLButtonElement) { setViewAnchor(undefined); setMoreAnchor(undefined); setAnnotationsAnchor(undefined); setSearchAnchor(undefined); setBookmarksAnchor(anchor) }
  function openSearch(anchor: HTMLButtonElement) { setViewAnchor(undefined); setMoreAnchor(undefined); setAnnotationsAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(anchor) }
  function openAnnotations(anchor: HTMLButtonElement) { setViewAnchor(undefined); setMoreAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(undefined); setAnnotationsAnchor(anchor) }
  function captureSelection() { if (state.mode !== 'reading') return; const result = createTextAnchorFromSelection(window.getSelection(), { sections, root: articleRef.current ?? undefined }); if ('reason' in result) return; const range = window.getSelection()?.getRangeAt(0); if (!range) return; const rect = range.getBoundingClientRect(); setSelectionAnchor(result); setSelectionPosition({ top: Math.max(12, rect.bottom + 8), left: Math.min(Math.max(12, rect.left), Math.max(12, window.innerWidth - 360)) }) }
  function clearSelection() { window.getSelection()?.removeAllRanges(); setSelectionAnchor(undefined); setSelectionPosition(undefined) }
  async function saveAnnotation(pending: { segments: TextAnchorSegment[]; quote: string; anchorKey: string }, color: AnnotationColor, note?: string) { const repository = typeof storage.getAnnotationRepository === 'function' ? storage.getAnnotationRepository() : undefined; if (!repository || findAnnotationOverlap(annotations, pending.segments)) return; try { await repository.add({ resourceKey, segments: pending.segments, quote: pending.quote, color, note }); setAnnotations(await repository.listForResource(resourceKey)); clearSelection(); setEditor(undefined) } catch { /* Local annotation storage is optional; Reader remains usable. */ } }
  function openAnnotationEditor(annotation: ReaderAnnotation, target: HTMLElement) { clearSelection(); setEditor({ anchor: target, annotation, color: annotation.color }) }
  async function saveEditor(note: string, color: AnnotationColor) { const repository = typeof storage.getAnnotationRepository === 'function' ? storage.getAnnotationRepository() : undefined; if (editor?.annotation && repository) { const updated = await repository.update(editor.annotation.id, { note: note.trim() || undefined, color }); if (updated) setAnnotations(await repository.listForResource(resourceKey)); setEditor(undefined) } else if (editor?.pending) await saveAnnotation(editor.pending, color, note.trim() || undefined) }
  function openBookmark(bookmark: Bookmark) { setBookmarksAnchor(undefined); if (bookmark.locator.kind !== 'pdf') return; const pageNumber = bookmark.locator.pageNumber; setState((current) => ({ ...current, page: clampPdfPage(pageNumber, sections.length) })); window.requestAnimationFrame(() => stageRef.current?.scrollTo({ top: 0, behavior: 'auto' })) }
  function goToLocator(locator: ReaderLocator) { if (locator.kind !== 'pdf') return; setState((current) => ({ ...current, page: clampPdfPage(locator.pageNumber, sections.length) })); window.requestAnimationFrame(() => stageRef.current?.scrollTo({ top: 0, behavior: 'auto' })) }
  function openSearchResult(result: import('../reader-search').ReaderSearchResult) { const current = currentLocator(); navigationHistory.current.push(current); setHasSearchHistory(true); void flushLocation(); setSearchAnchor(undefined); goToLocator(result.locator) }
  function backFromSearch() { const previous = navigationHistory.current.back(); if (previous) { setHasSearchHistory(navigationHistory.current.canGoBack()); goToLocator(previous) } else { setHasSearchHistory(false); onBack() } }
  useReaderSearchShortcut({ open: () => { const anchor = globalThis.document.querySelector<HTMLButtonElement>('[aria-label="Search in current book"]'); if (anchor) openSearch(anchor) }, focus: () => searchPanelRef.current?.focusAndSelect(), openAlready: Boolean(searchAnchor) })
  useEffect(() => { const onKey = (event: globalThis.KeyboardEvent) => { if (event.repeat || isReaderKeyboardEventBlocked(event)) return; if (event.key === 'ArrowLeft' || event.key === 'PageUp') { event.preventDefault(); changePageBy(-1) } if (event.key === 'ArrowRight' || event.key === 'PageDown') { event.preventDefault(); changePageBy(1) } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [changePageBy])
  const clickPage = (event: MouseEvent<HTMLElement>) => { if (!shouldToggleReaderChrome({ currentTarget: event.currentTarget, defaultPrevented: event.defaultPrevented, selectedText: window.getSelection()?.toString() ?? '', target: event.target })) return; if (isMobile) { if (visible) hide(); else reveal() } else reveal() }
  if (error) return <div className="reader-shell reader-message"><h1>Unable to open this PDF</h1><p>{error}</p><Link to="/library">Return to Library</Link></div>
  const label = `Page ${state.page} of ${sections.length}`
  const layout = resolveReaderLayout(settings, isMobile)
  const effectiveZoomMode = state.zoomMode === 'comfortable' && isMobile ? 'fit-width' : state.zoomMode
  return <div className="reader-shell pdf-reader" onClick={clickPage} onPointerUp={() => { if (state.mode === 'original' && window.getSelection()?.toString().trim()) { setOriginalLayoutNotice(true); window.setTimeout(() => setOriginalLayoutNotice(false), 3000) } }}><ReaderChrome backLabel={hasSearchHistory ? 'Back to previous reading position' : 'Back to Library'} bookTitle={imported.metadata.title} chapterLabel={label} chromeRef={chromeRef} isMobile={isMobile} onBack={backFromSearch} onMore={(target) => { setViewAnchor(undefined); setAnnotationsAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(undefined); setMoreAnchor(target) }} onSettings={(target) => { setMoreAnchor(undefined); setAnnotationsAnchor(undefined); setBookmarksAnchor(undefined); setSearchAnchor(undefined); setViewAnchor(target) }} onToggleBookmark={() => { void toggleBookmark() }} onOpenBookmarks={openBookmarks} onOpenSearch={openSearch} bookmarkActive={Boolean(currentBookmark())} pdf visible={visible} /><ReaderChromeRevealZone onReveal={reveal} visible={visible} />
    {state.mode === 'reading' ? <main className="reader-main" onPointerUp={captureSelection}><article className={`reader-article ${layout.className}`} data-reader-section-id={sections[state.page - 1]?.id} ref={articleRef} style={layout.styleVariables as CSSProperties}><header className="reader-chapter-heading"><p>Reading view — Beta<br />Complex layouts may change.</p></header><div className="reader-prose"><DocumentBlockRenderer annotations={annotations} blocks={sections[state.page - 1]?.blocks ?? []} onAnnotationClick={openAnnotationEditor} /></div></article></main> : <main className="pdf-reader__stage" ref={stageRef}><PdfPageNavigation chromeVisible={visible} isMobile={isMobile} onNext={() => changePageBy(1)} onPrevious={() => changePageBy(-1)} page={state.page} total={sections.length} />{pageError ? <div className="reader-message"><p>This PDF page could not be rendered.</p><button onClick={() => { setPageError(false); setRetry((value) => value + 1) }} type="button">Retry</button><button onClick={onBack} type="button">Return to Library</button></div> : document ? <PdfPage availableSize={stageSize} document={document} key={retry} onError={reportPageError} onScale={setScale} pageNumber={state.page} rotation={state.rotation} selectable={capabilities.supportsTextSelection} zoom={state.zoom} zoomMode={effectiveZoomMode} /> : <p>Loading original layout…</p>}</main>}
    {selectionAnchor && selectionPosition && <div className="selection-toolbar-host" style={selectionPosition}><SelectionToolbar isMobile={isMobile} onAddNote={() => { if (selectionAnchor && articleRef.current) { const pending = selectionAnchor; setSelectionAnchor(undefined); setSelectionPosition(undefined); setEditor({ anchor: articleRef.current, pending, color: 'lavender' }) } }} onCancel={clearSelection} onHighlight={(color) => { void saveAnnotation(selectionAnchor, color) }} /></div>}
    {viewAnchor && <AdaptivePanel anchorElement={viewAnchor} isMobile={isMobile} label="PDF view settings" onClose={() => setViewAnchor(undefined)} variant="settings"><PdfViewSettingsPanel mode={state.zoomMode} onMode={(zoomMode) => setState((current) => ({ ...current, zoomMode }))} onRotate={() => setState((current) => ({ ...current, rotation: (current.rotation + 90) % 360 }))} onZoom={zoom} percent={Math.round(scale * 100)} /></AdaptivePanel>}
    {moreAnchor && <AdaptivePanel anchorElement={moreAnchor} isMobile={isMobile} label="PDF options" onClose={() => setMoreAnchor(undefined)} variant="more"><section className="reader-more-menu"><h2>More</h2><button onClick={() => openAnnotations(moreAnchor)} type="button">Highlights &amp; Notes</button><button onClick={() => { setState((current) => ({ ...current, mode: current.mode === 'original' ? 'reading' : 'original' })); setMoreAnchor(undefined) }} disabled={!capabilities.reflowable} type="button">{state.mode === 'original' ? 'Reading view — Beta' : 'Original layout'} {!capabilities.reflowable && <span>No selectable text was found. OCR reading view is not available yet.</span>}</button><button disabled={state.page <= 1} onClick={() => changePageBy(-1)} type="button">Previous page</button><button disabled={state.page >= sections.length} onClick={() => changePageBy(1)} type="button">Next page</button></section></AdaptivePanel>}
    {bookmarksAnchor && <AdaptivePanel anchorElement={bookmarksAnchor} isMobile={isMobile} label="Bookmarks" onClose={() => setBookmarksAnchor(undefined)} variant="bookmarks"><ReaderBookmarksPanel bookmarks={bookmarks} onDelete={(bookmark) => { void getBookmarkRepository().remove(bookmark.id).then(async () => setBookmarks(await getBookmarkRepository().listForResource(resourceKey))).catch(() => undefined) }} onOpen={openBookmark} /></AdaptivePanel>}
    {annotationsAnchor && <AdaptivePanel anchorElement={annotationsAnchor} isMobile={isMobile} label="Highlights & Notes" onClose={() => setAnnotationsAnchor(undefined)} variant="more"><HighlightsNotesPanel annotations={annotations} locationLabel={(annotation) => annotationLocationLabel(annotation, sections)} onDelete={(annotation) => { const repository = typeof storage.getAnnotationRepository === 'function' ? storage.getAnnotationRepository() : undefined; if (repository) void repository.remove(annotation.id).then(async () => setAnnotations(await repository.listForResource(resourceKey))).catch(() => undefined) }} onEdit={(annotation) => setEditor({ anchor: annotationsAnchor, annotation, color: annotation.color })} onOpen={(annotation) => { const first = annotation.segments[0]; if (first) { setState((current) => ({ ...current, mode: 'reading', page: Math.min(sections.length, first.sectionIndex + 1) })); setAnnotationsAnchor(undefined) } }} /></AdaptivePanel>}
    {editor && <AdaptivePanel anchorElement={editor.anchor} isMobile={isMobile} label={editor.annotation ? 'Edit highlight' : 'Add note'} onClose={() => setEditor(undefined)} variant="more"><AnnotationEditor annotation={editor.annotation} color={editor.color} note={editor.annotation?.note} onCancel={() => setEditor(undefined)} onColor={(color) => setEditor((current) => current ? { ...current, color } : current)} onDelete={editor.annotation ? () => { const repository = typeof storage.getAnnotationRepository === 'function' ? storage.getAnnotationRepository() : undefined; if (repository) void repository.remove(editor.annotation!.id).then(async () => { setAnnotations(await repository.listForResource(resourceKey)); setEditor(undefined) }) } : undefined} onSave={(note, color) => { void saveEditor(note, color) }} quote={editor.annotation?.quote ?? editor.pending?.quote ?? ''} /></AdaptivePanel>}
    {searchAnchor && <AdaptivePanel anchorElement={searchAnchor} isMobile={isMobile} label="Search in current book" onClose={() => setSearchAnchor(undefined)} variant="search"><ReaderSearchPanel kind="pdf" onSelect={openSearchResult} ref={searchPanelRef} resourceKey={resourceKey} sections={sections} /></AdaptivePanel>}
    {originalLayoutNotice && <p aria-live="polite" className="reader-annotation-message">Highlights and notes are currently available in Reading View.</p>}
  </div>
}
