import { useEffect, useMemo, useRef, useState } from 'react'
import { ChevronLeft, ChevronRight, RotateCw, ZoomIn, ZoomOut } from 'lucide-react'
import type { DocumentSection, ImportedDocument, ReaderLocation } from '../../../domain/documents'
import { getDocumentRepository, getReadingActivityRepository } from '../../../storage'
import { DocumentBlockRenderer } from './DocumentBlockRenderer'
import type { PDFDocumentProxy, RenderTask } from 'pdfjs-dist'

type ZoomMode = 'comfortable' | 'fit-width' | 'fit-page' | 'actual' | 'custom'
type PdfState = { page: number; mode: 'original' | 'reading'; zoomMode: ZoomMode; zoom: number; rotation: number }
const dpr = () => Math.min(window.devicePixelRatio || 1, 2)
function scaleFor(mode: ZoomMode, width: number, height: number, page: { width: number; height: number }, custom: number) { if (mode === 'actual' || mode === 'custom') return custom; if (mode === 'fit-page') return Math.min(Math.max(0.2, (width - 32) / page.width), Math.max(.2, (height - 120) / page.height)); return Math.max(.2, (Math.min(mode === 'comfortable' ? 960 : width - 32, width - 32)) / page.width) }

export function PdfDocumentReader({ document, source, sections, capabilities, initialLocation, isMobile, onBack }: { document: ImportedDocument; source: Blob; sections: DocumentSection[]; capabilities: { reflowable: boolean; supportsTextSelection: boolean }; initialLocation?: ReaderLocation; isMobile: boolean; onBack: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const hostRef = useRef<HTMLDivElement>(null); const taskRef = useRef<RenderTask | undefined>(undefined); const pdfRef = useRef<PDFDocumentProxy | undefined>(undefined); const [error, setError] = useState<string>(); const [state, setState] = useState<PdfState>(() => ({ page: initialLocation?.pdf?.pageNumber ?? ((initialLocation?.sectionIndex ?? 0) + 1), mode: initialLocation?.pdf?.mode ?? 'original', zoomMode: initialLocation?.pdf?.zoomMode ?? (isMobile ? 'fit-width' : 'comfortable'), zoom: initialLocation?.pdf?.zoom ?? 1, rotation: initialLocation?.pdf?.rotation ?? 0 })); const [ready, setReady] = useState(false)
  useEffect(() => { let cancelled = false; let loading: { destroy: () => Promise<void> } | undefined; void (async () => { try { const pdfjs = await import('pdfjs-dist'); const worker = await import('pdfjs-dist/build/pdf.worker.min.mjs?url'); pdfjs.GlobalWorkerOptions.workerSrc = worker.default; const task = pdfjs.getDocument({ data: new Uint8Array(await source.arrayBuffer()), disableAutoFetch: true, disableRange: true, isEvalSupported: false }); loading = task; const pdf = await task.promise; if (cancelled) { await pdf.destroy(); return } pdfRef.current = pdf; setReady(true) } catch (caught) { if (!cancelled) setError(caught instanceof Error ? caught.message : 'This PDF could not be opened.') } })(); return () => { cancelled = true; taskRef.current?.cancel(); const pdf = pdfRef.current; pdfRef.current = undefined; void (pdf?.destroy() ?? loading?.destroy()) } }, [source])
  useEffect(() => { if (!ready || state.mode !== 'original') return; let cancelled = false; const render = async () => { const pdf = pdfRef.current; const canvas = canvasRef.current; const host = hostRef.current; if (!pdf || !canvas || !host) return; taskRef.current?.cancel(); const page = await pdf.getPage(state.page); if (cancelled) return; const base = page.getViewport({ scale: 1, rotation: state.rotation }); const scale = scaleFor(state.zoomMode, host.clientWidth, host.clientHeight, base, state.zoom); const viewport = page.getViewport({ scale, rotation: state.rotation }); const ratio = dpr(); canvas.width = Math.ceil(viewport.width * ratio); canvas.height = Math.ceil(viewport.height * ratio); canvas.style.width = `${viewport.width}px`; canvas.style.height = `${viewport.height}px`; const context = canvas.getContext('2d')!; context.setTransform(ratio, 0, 0, ratio, 0, 0); const task = page.render({ canvas, canvasContext: context, viewport }); taskRef.current = task; try { await task.promise } catch (renderError) { if (!(renderError instanceof Error && /cancel/i.test(renderError.name))) throw renderError } finally { page.cleanup() } }; void render(); const observer = new ResizeObserver(() => { if (state.zoomMode !== 'actual' && state.zoomMode !== 'custom') void render() }); observer.observe(hostRef.current!); return () => { cancelled = true; taskRef.current?.cancel(); observer.disconnect() } }, [ready, state])
  useEffect(() => { if (!ready) return; const location: ReaderLocation = { documentId: document.id, sectionId: `page-${state.page}`, sectionIndex: state.page - 1, progressPercent: 0, updatedAt: new Date().toISOString(), pdf: { mode: state.mode, zoomMode: state.zoomMode, zoom: state.zoom, rotation: state.rotation, pageNumber: state.page } }; void getDocumentRepository().saveLocation(location); void getReadingActivityRepository().recordProgress({ contentKind: 'imported', documentId: document.id, sectionId: location.sectionId, sectionIndex: location.sectionIndex, locationLabel: `Page ${state.page} of ${sections.length}`, lastReadAt: location.updatedAt }) }, [document.id, ready, sections.length, state])
  const controls = useMemo(() => <div className="pdf-controls"><button onClick={onBack} type="button">Back</button><button disabled={state.page <= 1} onClick={() => setState((s) => ({ ...s, page: s.page - 1 }))} type="button"><ChevronLeft size={18} />Previous</button><span>Page {state.page} of {sections.length}</span><button disabled={state.page >= sections.length} onClick={() => setState((s) => ({ ...s, page: s.page + 1 }))} type="button">Next<ChevronRight size={18} /></button><select aria-label="PDF zoom" onChange={(event) => setState((s) => ({ ...s, zoomMode: event.target.value as ZoomMode }))} value={state.zoomMode}><option value="comfortable">Comfortable</option><option value="fit-width">Fit width</option><option value="fit-page">Fit page</option><option value="actual">Actual size</option></select><button aria-label="Zoom out" onClick={() => setState((s) => ({ ...s, zoomMode: 'custom', zoom: Math.max(.25, s.zoom - .1) }))} type="button"><ZoomOut size={18} /></button><button aria-label="Zoom in" onClick={() => setState((s) => ({ ...s, zoomMode: 'custom', zoom: Math.min(3, s.zoom + .1) }))} type="button"><ZoomIn size={18} /></button><button aria-label="Rotate clockwise" onClick={() => setState((s) => ({ ...s, rotation: (s.rotation + 90) % 360 }))} type="button"><RotateCw size={18} /></button></div>, [onBack, sections.length, state])
  if (error) return <div className="reader-message"><h1>Unable to open this PDF</h1><p>{error}</p></div>
  if (state.mode === 'reading') return <div className="pdf-reader"><div className="pdf-controls"><button onClick={() => setState((s) => ({ ...s, mode: 'original' }))} type="button">Original layout</button></div><article className="reader-article reader-article--left pdf-beta-note"><p>Reading view — Beta. Complex layouts may change.</p><DocumentBlockRenderer blocks={sections[state.page - 1]?.blocks ?? []} /></article></div>
  return <section className="pdf-reader" ref={hostRef}><div className="pdf-reader__chrome">{controls}<button disabled={!capabilities.reflowable} onClick={() => setState((s) => ({ ...s, mode: 'reading' }))} type="button">Reading view — Beta</button></div><div className="pdf-reader__stage"><canvas aria-label={`PDF page ${state.page}`} ref={canvasRef} /></div>{!ready && <p>Loading original layout…</p>}</section>
}
