import type { ReadingActivity, ReadingContentKind } from '../domain/reading-activity'
import { readingActivityKey } from '../domain/reading-activity'
import { openDatabase, requestResult, transactionComplete } from './database'

export interface ReadingActivityRepository { recordOpen(contentKind: ReadingContentKind, documentId: string, openedAt?: string): Promise<ReadingActivity>; recordProgress(activity: Omit<ReadingActivity, 'key' | 'firstOpenedAt' | 'lastOpenedAt'> & { lastOpenedAt?: string }): Promise<ReadingActivity>; getActivity(contentKind: ReadingContentKind, documentId: string): Promise<ReadingActivity | undefined>; listActivities(): Promise<ReadingActivity[]>; deleteActivity(key: string): Promise<void> }
function later(previous: string | undefined, value: string) { return !previous || previous < value ? value : previous }
function changed() { if (typeof window !== 'undefined') window.dispatchEvent(new Event('readingactivitychanged')) }
export class MemoryReadingActivityRepository implements ReadingActivityRepository {
  private readonly activities = new Map<string, ReadingActivity>()
  async recordOpen(contentKind: ReadingContentKind, documentId: string, openedAt = new Date().toISOString()) { const key = readingActivityKey(contentKind, documentId); const current = this.activities.get(key); const next: ReadingActivity = { key, contentKind, documentId, firstOpenedAt: current?.firstOpenedAt ?? openedAt, lastOpenedAt: later(current?.lastOpenedAt, openedAt), ...(current?.lastReadAt ? { lastReadAt: current.lastReadAt } : {}), ...(current?.sectionId ? { sectionId: current.sectionId } : {}), ...(current?.sectionIndex !== undefined ? { sectionIndex: current.sectionIndex } : {}), ...(current?.locationLabel ? { locationLabel: current.locationLabel } : {}), ...(current?.progressPercent !== undefined ? { progressPercent: current.progressPercent } : {}) }; this.activities.set(key, next); changed(); return next }
  async recordProgress(input: Omit<ReadingActivity, 'key' | 'firstOpenedAt' | 'lastOpenedAt'> & { lastOpenedAt?: string }) { const open = await this.recordOpen(input.contentKind, input.documentId, input.lastOpenedAt ?? new Date().toISOString()); const next: ReadingActivity = { ...open, ...input, key: open.key, firstOpenedAt: open.firstOpenedAt, lastOpenedAt: later(open.lastOpenedAt, input.lastOpenedAt ?? open.lastOpenedAt), lastReadAt: later(open.lastReadAt, input.lastReadAt ?? new Date().toISOString()) }; this.activities.set(next.key, next); changed(); return next }
  async getActivity(contentKind: ReadingContentKind, documentId: string) { return this.activities.get(readingActivityKey(contentKind, documentId)) }
  async listActivities() { return [...this.activities.values()] }
  async deleteActivity(key: string) { this.activities.delete(key); changed() }
}
export class IndexedDbReadingActivityRepository implements ReadingActivityRepository {
  private async update(key: string, create: () => ReadingActivity, update: (current: ReadingActivity) => ReadingActivity) { const db = await openDatabase(); try { const transaction = db.transaction('readingActivity', 'readwrite'); const store = transaction.objectStore('readingActivity'); const current = await requestResult(store.get(key)) as ReadingActivity | undefined; const result = current ? update(current) : create(); const complete = transactionComplete(transaction); await Promise.all([requestResult(store.put(result)), complete]); changed(); return result } finally { db.close() } }
  recordOpen(contentKind: ReadingContentKind, documentId: string, openedAt = new Date().toISOString()) { const key = readingActivityKey(contentKind, documentId); return this.update(key, () => ({ key, contentKind, documentId, firstOpenedAt: openedAt, lastOpenedAt: openedAt }), (current) => ({ ...current, lastOpenedAt: later(current.lastOpenedAt, openedAt) })) }
  recordProgress(input: Omit<ReadingActivity, 'key' | 'firstOpenedAt' | 'lastOpenedAt'> & { lastOpenedAt?: string }) { const openedAt = input.lastOpenedAt ?? new Date().toISOString(); const readAt = input.lastReadAt ?? openedAt; const key = readingActivityKey(input.contentKind, input.documentId); return this.update(key, () => ({ ...input, key, firstOpenedAt: openedAt, lastOpenedAt: openedAt, lastReadAt: readAt }), (current) => ({ ...current, ...input, key, firstOpenedAt: current.firstOpenedAt, lastOpenedAt: later(current.lastOpenedAt, openedAt), lastReadAt: later(current.lastReadAt, readAt) })) }
  async getActivity(contentKind: ReadingContentKind, documentId: string) { const db = await openDatabase(); try { return await requestResult(db.transaction('readingActivity').objectStore('readingActivity').get(readingActivityKey(contentKind, documentId))) as ReadingActivity | undefined } finally { db.close() } }
  async listActivities() { const db = await openDatabase(); try { return await requestResult(db.transaction('readingActivity').objectStore('readingActivity').getAll()) as ReadingActivity[] } finally { db.close() } }
  async deleteActivity(key: string) { const db = await openDatabase(); try { const transaction = db.transaction('readingActivity', 'readwrite'); const complete = transactionComplete(transaction); await Promise.all([requestResult(transaction.objectStore('readingActivity').delete(key)), complete]); changed() } finally { db.close() } }
}
let repository: ReadingActivityRepository | undefined
export function getReadingActivityRepository() { repository ??= new IndexedDbReadingActivityRepository(); return repository }
