import JSZip from 'jszip'
import { DOMParser, XMLSerializer } from '@xmldom/xmldom'
import { beforeAll, describe, expect, it, vi } from 'vitest'
import type { DocumentSource } from '../domain/documents'

const epubCalls = vi.hoisted(() => ({ opens: 0 }))
vi.mock('epubjs', async (importOriginal) => { const actual = await importOriginal<typeof import('epubjs')>(); return { ...actual, default: (...args: Parameters<typeof actual.default>) => { epubCalls.opens += 1; return actual.default(...args) } } })
import { epubAdapter } from './epub-adapter'

beforeAll(() => { Object.assign(globalThis, { DOMParser, XMLSerializer, window: globalThis }); const elementPrototype = Object.getPrototypeOf(new DOMParser().parseFromString('<root/>', 'application/xml').documentElement); if (!Object.hasOwn(elementPrototype, 'children')) Object.defineProperty(elementPrototype, 'children', { get() { return Array.from(this.childNodes).filter((node) => (node as Node).nodeType === 1) } }) })

type Chapter = { name: string; body: string }
async function fixture({ title = 'A Small Book', includeSpine = true, chapters = [{ name: 'one.xhtml', body: '<h1>One</h1><p>First.</p>' }, { name: 'two.xhtml', body: '<h2>Two</h2><p>Second.</p>' }], nav = true }: { title?: string; includeSpine?: boolean; chapters?: Chapter[]; nav?: boolean } = {}) {
  const zip = new JSZip(); zip.file('mimetype', 'application/epub+zip'); zip.file('META-INF/container.xml', '<?xml version="1.0"?><container><rootfiles><rootfile full-path="OPS/book.opf" media-type="application/oebps-package+xml"/></rootfiles></container>')
  const manifest = chapters.map((chapter, index) => `<item id="c${index}" href="${chapter.name}" media-type="application/xhtml+xml"/>`).join('') + (nav ? '<item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>' : '')
  const spine = includeSpine ? `<spine>${chapters.map((_, index) => `<itemref idref="c${index}"/>`).join('')}</spine>` : ''
  zip.file('OPS/book.opf', `<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">sample</dc:identifier><dc:title>${title}</dc:title><dc:creator>Ada</dc:creator><dc:language>en</dc:language><dc:description>A description</dc:description></metadata><manifest>${manifest}</manifest>${spine}</package>`)
  chapters.forEach((chapter) => zip.file(`OPS/${chapter.name}`, `<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Chapter</title></head><body>${chapter.body}</body></html>`))
  if (nav) zip.file('OPS/nav.xhtml', `<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>Contents</title></head><body><nav epub:type="toc"><ol>${chapters.map((chapter, index) => `<li><a href="${chapter.name}">Navigation ${index + 1}</a></li>`).join('')}</ol></nav></body></html>`)
  const bytes = await zip.generateAsync({ type: 'uint8array' }); const blob = new Blob([bytes as unknown as ArrayBuffer]); return { blob, fileName: 'sample.epub', size: blob.size } satisfies DocumentSource
}

describe('EPUB adapter', () => {
  it('uses epub.js for a minimal EPUB, metadata, navigation, and spine order', async () => { epubCalls.opens = 0; const parsed = await epubAdapter.parse(await fixture()); expect(epubCalls.opens).toBe(1); expect(parsed.metadata).toMatchObject({ title: 'A Small Book', author: 'Ada', language: 'en', description: 'A description', sectionCount: 2 }); expect(parsed.sections.map(({ id, order, title }) => ({ id, order, title }))).toEqual([{ id: 'section-0', order: 0, title: 'Navigation 1' }, { id: 'section-1', order: 1, title: 'Navigation 2' }]); expect(parsed.capabilities).toMatchObject({ reflowable: true, supportsTextSelection: true, supportsTableOfContents: true, supportsPagination: false, supportsSearch: false, supportsReadAloud: false }) })
  it('converts safe XHTML structure into stable reader blocks', async () => { const parsed = await epubAdapter.parse(await fixture({ chapters: [{ name: 'chapter.xhtml', body: '<h2>Heading</h2><p>Paragraph <img src="https://bad.example/a.png" onerror="boom"/>text.</p><blockquote>Quote</blockquote><ul><li>Bullet</li></ul><ol><li>Number</li></ol><hr epub:type="pagebreak"/><script>bad()</script><iframe src="https://bad.example"></iframe>' }] })); expect(parsed.sections[0].blocks).toEqual([{ id: 'block-0', type: 'heading', text: 'Heading', order: 0, level: 2 }, { id: 'block-1', type: 'paragraph', text: 'Paragraph text.', order: 1 }, { id: 'block-2', type: 'blockquote', text: 'Quote', order: 2 }, { id: 'block-3', type: 'list-item', text: 'Bullet', order: 3, ordered: false }, { id: 'block-4', type: 'list-item', text: 'Number', order: 4, ordered: true }, { id: 'block-5', type: 'page-break', text: '', order: 5 }]) })
  it('rejects invalid ZIP data and missing package/spine data', async () => { const bad = new Blob(['not a zip']); await expect(epubAdapter.supports({ blob: bad, fileName: 'bad.epub', size: bad.size })).resolves.toBe(false); await expect(epubAdapter.parse({ blob: bad, fileName: 'bad.epub', size: bad.size })).rejects.toMatchObject({ code: 'invalid-document' }); await expect(epubAdapter.parse(await fixture({ includeSpine: false }))).rejects.toMatchObject({ code: 'invalid-document' }) })
  it('uses the file name for missing title and rejects empty spine content', async () => { const missingTitle = await fixture({ title: '' }); const parsed = await epubAdapter.parse({ ...missingTitle, fileName: 'fallback.epub' }); expect(parsed.metadata.title).toBe('fallback'); await expect(epubAdapter.parse(await fixture({ chapters: [{ name: 'empty.xhtml', body: '<script>bad()</script><iframe></iframe>' }] }))).rejects.toMatchObject({ code: 'empty-file' }) })
  it('only reads a signature slice in supports and the complete blob once in parse', async () => { const original = await fixture(); let fullReads = 0; let slices = 0; const blob = { size: original.blob.size, arrayBuffer: async () => { fullReads += 1; return original.blob.arrayBuffer() }, slice: (...args: Parameters<Blob['slice']>) => { slices += 1; return original.blob.slice(...args) } } as unknown as Blob; const source = { ...original, blob }; await expect(epubAdapter.supports(source)).resolves.toBe(true); expect({ fullReads, slices }).toEqual({ fullReads: 0, slices: 1 }); await epubAdapter.parse(source); expect(fullReads).toBe(1) })
})
